functionsDirectory = "/Users/rvmpay/Downloads/Farhan/One-Stop-API/dist/functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/rvmpay/Downloads/Farhan/One-Stop-API/dist"
publishOrigin = "config"
functions = "/Users/rvmpay/Downloads/Farhan/One-Stop-API/dist/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]