[build]
  publish = "dist"   # This is where your static files will go
  functions = "dist/functions"   # Make sure this points to your compiled functions

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
